"MacVim - Luigi Luongo

set guifont=monospace:h20            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set incsearch											" Set incremental search

"set guioptions-=T                 " Hide toolbar.

set background=light              " Background.
set lines=768 columns=1024          " Window dimensions.
set guioptions-=r                 " Don't show right scrollbar
set autoindent
set shiftwidth=2		" > indent
set tabstop=2			  " Tabstop 2 space

set viewdir=$HOME/.vim/views
" Map command
map <Leader>of	:FufFile		
map <Leader>od	:FufDir
map <C-o> \of <Enter>
map <C-d> :wincmd j <Enter>
map <C-u> :wincmd k <Enter>
map <C-l> :wincmd l <Enter>
map <C-r> :wincmd h <Enter>
" Imap => mapping 
imap ee <Esc>


